# encoding: UTF-8

control 'CMS-ARS-3.1-AU-03(02)' do
  title 'Centralized Management of Planned Audit Record Content '
  desc  "Control:
    The information system provides centralized management and configuration of
the content to be captured in audit records generated by individual components
throughout the information system.
  "
  desc  'check', "
    Assessment Objective:
    Determine if the organization has implemented all elements of this control
as described in the control statements and implementation standard(s).

    Assessment Methods and Objects:
    Examine: Audit and accountability policy; procedures addressing content of
audit records; information system design documentation; list of
organization-defined auditable events; information system configuration
settings and associated documentation; information system audit records; other
relevant documents or records.Examine: Information system provides centralized
management and configuration of the content to be captured. Examples: 1.  Audit
data is collected and analyzed centrally within the organization; and 2.  Audit
data is available to the CCIC for analysis.Test: Automated mechanisms
implementing centralized management of audit record content.
  "
  desc  'fix', "
    Implementation Standards:
    High:

    Std.1 - Centralized audit repositories must be searchable by the CCIC:
(a) Information is available to the CCIC in a format compliant with CMS and
Federal (e.g., Continuous Diagnostics and Mitigation) requirements; and  (b)
Centralized audit repository record sources include systems, appliances,
devices, services, and applications (including databases). Std.2 - As required
by CMS, raw audit records must be available in an unaltered format to the CCIC.

    Supplemental Guidance:
    This control enhancement requires that the content to be captured in audit
records be configured from a central location (necessitating automation).
Organizations coordinate the selection of required audit content to support the
centralized management and configuration capability provided by the information
system.Audit records contain evidence that can be used in the investigation of
compromised systems. To prevent this evidence from being compromised, it must
be sent to a separate system continuously. Methods for sending audit records
include, but are not limited to, system audit tools used to send logs directly
to another host or through the system's syslog service to another
host. Contact your CRA or the CCIC for the list of compliant formats. All
security information and results, complete and unedited, from relevant
automated tools must be available to the CCIC upon their request.  The
information must be made available in a format, and within a timeframe, to be
agreed-upon with the CCIC and consistent with all other safeguards required by
the ARS.
  "
  impact 0.5
  tag severity: 'medium'
  tag nist: ['AU-3(02)']
  tag nist_family: 'Audit and Accountability'
  tag cms_ars_type: 'Mandatory Enhancement'
  tag cms_ars_baseline: ['High']
  tag cms_ars_assurance: nil
  tag cms_ars_priority: 'P1'
  tag cms_ars_reference_policy: " NIST SP: 800-37, 800-39, 800-137; OMB Memo:
M-14-03, M-15-01, M-16-04"
  tag related_controls: ['AU-6', 'AU-7']

  describe "A manual review/attestation is required to address interview/examine assessment objectives for this control" do
    skip "A manual review/attestation is required to address interview/examine assessment objectives for this control"
  end
end
