# encoding: UTF-8

control 'CMS-ARS-3.1-CA-07' do
  title 'Continuous Monitoring '
  desc  "Control:
    The organization develops a continuous monitoring strategy and implements a
continuous monitoring program that includes: a. Establishment of defined
metrics (defined in the applicable system security plan) to be monitored based
on the organization security goals and objectives and in accordance with the
basic requirements set forth in NIST SP 800-137; b. Establishment of defined
frequencies (defined in the applicable system security plan), but no less than
once every 72 hours, for monitoring and defined frequencies (defined in the
applicable system security plan), but no less than once every 72 hours, for
assessments supporting such monitoring; c. Ongoing security control assessments
in accordance with the organizational continuous monitoring strategy; d.
Ongoing security status monitoring of organization-defined metrics in
accordance with the organizational continuous monitoring strategy; e.
Correlation and analysis of security-related information generated by
assessments and monitoring; f. Response actions to address results of the
analysis of security-related information; and g. Reporting the security status
of the organization and the information system to defined personnel or roles
(defined in the applicable system security plan) monthly.
  "
  desc  'check', "
    Assessment Objective:
    Determine if the organization has implemented all elements of this control
as described in the control statements and implementation standard(s).

    Assessment Methods and Objects:
    Examine: Security assessment and authorization policy; procedures
addressing continuous monitoring of information system security controls;
procedures addressing configuration management; system security plan; security
assessment report; plan of action and milestones; information system monitoring
records; configuration management records, security impact analyses; status
reports; and other relevant documents or records.Examine: Information system is
integrated into organizational and CMS continuous monitoring program.Interview:
Organizational personnel with continuous monitoring responsibilities;
organizational personnel with configuration management responsibilities.
  "
  desc  'fix', "
    Implementation Standards:
    High, Moderate & Low:

    Std.1 - When subject to a legal investigation (e.g., of an insider threat),
continuous monitoring records must be maintained until released by the
investigating authority.Std.2 - Monitors systems, appliances, devices, and
applications (including databases).Std.3 - The CCIC provides oversight of
information security and privacy, to include Security Information and Event
Management (SIEM), for each FISMA System operating by or on behalf of CMS.

    Supplemental Guidance:
    Continuous monitoring programs facilitate ongoing awareness of threats,
vulnerabilities, and information security to support organizational risk
management decisions. The terms 'continuous' and
'ongoing' imply that organizations assess/analyze
security controls and information security-related risks at a frequency
sufficient to support organizational risk-based decisions. The results of
continuous monitoring programs generate appropriate risk response actions by
organizations. Continuous monitoring programs also allow organizations to
maintain the security authorizations of information systems and common controls
over time in highly dynamic environments of operation with changing
mission/business needs, threats, vulnerabilities, and technologies. Having
access to security-related information on a continuing basis through
reports/dashboards gives organizational officials the capability to make more
effective and timely risk management decisions, including ongoing security
authorization decisions. Automation supports more frequent updates to security
authorization packages, hardware/software/firmware inventories, and other
system information. Effectiveness is further enhanced when continuous
monitoring outputs are formatted to provide information that is specific,
measurable, actionable, relevant, and timely. Continuous monitoring activities
are scaled in accordance with the security categories of information systems.

    Guidance for systems processing, storing, or transmitting PII (to include
PHI):

    The state of security controls can directly correlate to privacy risk.
Continuous monitoring supports the identification of issues that could result
in unauthorized access to sensitive information such as PII, data quality
issues, and other concerns, including privacy, that are supported by security
controls.

    Guidance for systems processing, storing, or transmitting PHI:

    Consider using automated tools and mechanisms for system activity review.
The effectiveness of continuous monitoring of various activities, for example,
failed or successful log-ins, inappropriate file access, detecting and
reporting on malicious code/viruses through network transmission, is enhanced
using approved automated tools.
  "
  impact 0.5
  tag severity: 'medium'
  tag nist: ['CA-7']
  tag nist_family: 'Security Assessment and Authorization'
  tag cms_ars_type: 'Mandatory'
  tag cms_ars_baseline: ['High', 'Moderate', 'Low']
  tag cms_ars_assurance: 'Assurance'
  tag cms_ars_priority: 'P3'
  tag cms_ars_reference_policy: " Code: 5 U.S.C. §552a(e)(10); FedRAMP
Rev. 4 Baseline; FISCAM: AS-1, SM-5; HHS: Policy for Monitoring Employee Use of
HHS IT Resources; HIPAA: 45 C.F.R. §164.308(a)(1)(ii)(D), 45 C.F.R.
§164.308(a)(8); 45 C.F.R. §164.308(a)(5)(ii)(C) HSPD 7: F(19);
NIST SP: 800-37, 800-39, 800-115, 800-137; OMB Memo: M-11-33, M-14-03, M-15-01,
M-16-04"
  tag related_controls: ['AR-4', 'CA-2', 'CA-5', 'CA-6', 'CM-3', 'CM-4',
'PM-6', 'PM-9', 'RA-5', 'SA-11', 'SA-12', 'SI-2', 'SI-4']

  describe "A manual review/attestation is required to address interview/examine assessment objectives for this control" do
    skip "A manual review/attestation is required to address interview/examine assessment objectives for this control"
  end
end
