# encoding: UTF-8

control 'CMS-ARS-3.1-CM-07(01)' do
  title 'Periodic Review '
  desc  "Control:
    The organization: (a) Reviews the information system no less often than
once every thirty (30) days to identify and eliminate unnecessary functions,
ports, protocols, and/or services;(b) Performs automated reviews of the
information system no less often than once every seventy-two (72) hours to
identify changes in functions, ports, protocols, and/or services; and (c)
Disables functions, ports, protocols, and services within the information
system deemed to be unnecessary and/or non-secure.
  "
  desc  'check', "
    Assessment Objective:
    Determine if the organization has implemented all elements of this control
as described in the control statements and implementation standard(s).

    Systems defined as CSPs:

    Determine if the organization has implemented all elements of this control
as described in the CSP control statements and implementation standard(s).

    Assessment Methods and Objects:
    Examine: Configuration management policy; configuration management plan;
procedures addressing least functionality in the information system; system
security plan; information system configuration settings and associated
documentation; security configuration checklists; and other relevant documents
or records.Examine: Information system provides the capability to identify
changes in configurations in an automated manner.Interview: Organizational
personnel with responsibilities for identifying and eliminating unnecessary
functions, ports, protocols, and services on the information system.
  "
  desc  'fix', "
    Implementation Standards:
    High & Moderate:

    Std.1 - Periodic configuration review results that are generated by
automated tools must be searchable by the CCIC:(a) Information is provided to
the CCIC in a format compliant with CMS and Federal (e.g., Continuous
Diagnostics and Mitigation) requirements;(b) Configuration review information
sources include systems, appliances, devices, services, and applications
(including databases); and(c) CCIC directed configuration automated periodic
review information collection rules/requests (e.g., sources, queries, data
calls) must be implemented/provided within the timeframe specified in the
request. Std.2 - Raw security information/results from relevant automated tools
must be available in an unaltered format to the CCIC.

    Systems defined as CSPs:

    High & Moderate:

    CSP.1 - CSPs must implement this Standard (CM-7(1) CSP.1) as a replacement
for the previous Implementation Standards for this Control(CM-7(1) Std.1 and
Std.2). The organization reviews the information system no less often than
quarterly to identify and eliminate unnecessary functions, ports, protocols,
and/or services.

    Supplemental Guidance:
    The organization can either determine the relative security of the
function, port, protocol, and/or service or base the security decision on the
assessment of other entities. Bluetooth, FTP, and peer-to-peer networking are
examples of less than secure protocols. Contact your CRA or the CCIC for the
list of compliant formats. All security information and results, complete and
unedited, from relevant automated tools must be available to the CCIC upon
their request.  The information must be made available in a format, and within
a timeframe, to be agreed-upon with the CCIC and consistent with all other
safeguards required by the ARS.
  "
  impact 0.5
  tag severity: 'medium'
  tag nist: ['CM-7(01)']
  tag nist_family: 'Configuration Management'
  tag cms_ars_type: 'Mandatory Enhancement'
  tag cms_ars_baseline: ['High', 'Moderate']
  tag cms_ars_assurance: nil
  tag cms_ars_priority: 'P1'
  tag cms_ars_reference_policy: " FedRAMP Rev. 4 Baseline; NIST SP: 800-37,
800-39, 800-137; OMB Memo: M-14-03, M-15-01, M-16-04"
  tag related_controls: ['AC-18', 'CM-7', 'IA-2']

  describe "A manual review/attestation is required to address interview/examine assessment objectives for this control" do
    skip "A manual review/attestation is required to address interview/examine assessment objectives for this control"
  end
end
