# encoding: UTF-8

control 'CMS-ARS-3.1-AU-08' do
  title 'Time Stamps '
  desc  "Control:
    The information system: a. Uses internal system clocks to generate time
stamps for audit records; and b. Records time stamps for audit records that can
be mapped to UTC or Greenwich Mean Time (GMT) and is accurate to within one
hundred (100) milliseconds.
  "
  desc  'check', "
    Assessment Objective:
    Determine if the organization has implemented all elements of this control
as described in the control statements and implementation standard(s).

    Assessment Methods and Objects:
    Examine: Audit and accountability policy; procedures addressing audit
reduction and report generation; information system design documentation; audit
reduction, review, and reporting tools; information system audit records; or
other relevant documents or records.Examine: Information system provides
required time stamping and synchronization.Interview: Organizational personnel
with information system audit review, analysis, and reporting
responsibilities.Test: Audit reduction and report generation capability.
  "
  desc  'fix', "
    Implementation Standards:

    Supplemental Guidance:
    Time stamps generated by the information system include date and time. Time
is commonly expressed in UTC, a modern continuation of GMT, or local time with
an offset from UTC. Granularity of time measurements refers to the degree of
synchronization between information system clocks and reference clocks, for
example, clocks synchronizing within hundreds of milliseconds or within tens of
milliseconds. Organizations may define different time granularities for
different system components. Time service can also be critical to other
security capabilities such as access control and identification and
authentication, depending on the nature of the mechanisms used to support those
capabilities. - The correlation of monitoring tools that usually work in
isolation (e.g., host monitoring, network monitoring, anti-virus software) can
provide an organization-wide view and in so doing, may reveal otherwise unseen
attack patterns; and - Consistent log timestamps facilitate effective event
correlation.
  "
  impact 0.5
  tag severity: 'medium'
  tag nist: ['AU-8']
  tag nist_family: 'Audit and Accountability'
  tag cms_ars_type: 'Mandatory'
  tag cms_ars_baseline: ['High', 'Moderate', 'Low']
  tag cms_ars_assurance: nil
  tag cms_ars_priority: 'P1'
  tag cms_ars_reference_policy: ' FedRAMP Rev. 4 Baseline; FISCAM: AC-5, AS-2'
  tag related_controls: ['AU-3', 'AU-12']

  describe "A manual review/attestation is required to address interview/examine assessment objectives for this control" do
    skip "A manual review/attestation is required to address interview/examine assessment objectives for this control"
  end
end
