# encoding: UTF-8

control 'CMS-ARS-3.1-SI-04(16)' do
  title 'Non-Mandatory: Correlate Monitoring Information '
  desc  "Control:
    The organization correlates information from monitoring tools employed
throughout the information system.
  "
  desc  'check', "
    Assessment Objective:
    Determine if the organization has implemented all elements of this control
as described in the control statements and implementation standard(s).

    Assessment Methods and Objects:
    Examine: System and information integrity policy; procedures addressing
information system monitoring tools and techniques; information system design
documentation; information system monitoring tools and techniques
documentation; information system configuration settings and associated
documentation; procedures addressing security monitoring tool data correlation;
and other relevant documents or records.Examine: Organization employs automated
tools to correlate security monitoring tool data collected throughout the
information system.Interview: Organizational personnel with information system
monitoring responsibilities.
  "
  desc  'fix', "
    Implementation Standards:

    Supplemental Guidance:
    Correlating information from different monitoring tools can provide a more
comprehensive view of information system activity. The correlation of
monitoring tools that usually work in isolation (e.g., host monitoring, network
monitoring, anti-virus software) can provide an organization-wide view and in
so doing, may reveal otherwise unseen attack patterns. Understanding the
capabilities/limitations of diverse monitoring tools and how to maximize the
utility of information generated by those tools can help organizations to
build, operate, and maintain effective monitoring programs.
  "
  impact 0.5
  tag severity: 'medium'
  tag nist: ['SI-4(16)']
  tag nist_family: 'System and Information Integrity'
  tag cms_ars_type: 'Non-Mandatory'
  tag cms_ars_baseline: []
  tag cms_ars_assurance: nil
  tag cms_ars_priority: 'P3'
  tag cms_ars_reference_policy: " Cybersecurity Enhancement Act of 2014;
FedRAMP Rev. 4 Baseline; OMB Memo: M-14-03, M-15-01"
  tag related_controls: ['AU-6']

  describe "A manual review/attestation is required to address interview/examine assessment objectives for this control" do
    skip "A manual review/attestation is required to address interview/examine assessment objectives for this control"
  end
end
